const LIGHT_COLOR = {
  BACKGROUND: '#FFFFFF',
  SUB_BACKGROUND: '#EAEBF4',
  ON_BACKGROUND_TEXT: '#000000',
  ON_SUB_BACKGROUND_TEXT: '#393D7A',
  ON_BACKGROUND_IMAGE: '#FFFFFF',
  BUTTON: '#02C8A3',
  ON_BUTTON: '#FFFFFF',
  FOOTER_BACKGROUND: '#40444F',
  ON_FOOTER_TEXT: '#BEC8E2',
  ON_FOOTER_SUB_TEXT: '#FFFFFF',
  TAB_BUTTON: '#B446BF',
};

const DARK_COLOR = {
  BACKGROUND: '#232323',
  SUB_BACKGROUND: '#2C2C2C',
  ON_BACKGROUND_TEXT: '#D3D8E8',
  ON_SUB_BACKGROUND_TEXT: '#8A96DC',
  ON_BACKGROUND_IMAGE: '#FFFFFF',
  BUTTON: '#00BA90',
  ON_BUTTON: '#D3D8E8',
  FOOTER_BACKGROUND: '#232323',
  ON_FOOTER_TEXT: '#BEC8E2',
  ON_FOOTER_SUB_TEXT: '#FFFFFF',
  TAB_BUTTON: '#B290B7',
};

export {
  LIGHT_COLOR as lightColor,
  DARK_COLOR as darkColor,
};
